### ISSUE TITLE
Limit animations to a div element

### ISSUE THREAD

**Issue by alefz3r0** [Haroenv/floating.js#19]
Is it possibile to reduce the scope of the animations to a div element, and not to the full page?

**Comment by Haroenv** [comment]
You could override the styles on `.float-container`, but since it's positioned absolutely, you'll need to calculate the place of your div manually. Here's an example:

https://codesandbox.io/s/awesome-dirac-ruivh?file=/src/index.js

```js
// get the position you want to emulate
const target = document.getElementById("target");
const rect = target.getBoundingClientRect();

// reposition the float container
const floatContainer = document.querySelector(".float-container");
floatContainer.style.top = rect.top + "px";
floatContainer.style.left = rect.left + "px";
floatContainer.style.width = rect.width + "px";
floatContainer.style.height = rect.height + "px";
```

However, this does mean that the floating items themselves will still go over the whole screen, so take that in account when choosing the number of items.

I'll close this now, since I don't work on floating often and open issues can be confusing, but I'd love to hear if that worked for you!
